### ISSUE TITLE
Broken Minimap Icon

### ISSUE THREAD

**Issue by arcadepro** [mrmaffen/auto-open-anything#1]
I don't think you've embedded the libraries correctly. If I load some other addons that implement ace libs the icon for your addon works fine.

I added the following to the .toc file and it fixed everything. I don't know much about ace so you'll need to look into this. If the embeds.xml is an alternative way to embed libs then maybe that file needs fixing rather than my quick fix.

```
Libs\LibStub\LibStub.lua
Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua
Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua
Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua
Libs\AceAddon-3.0\AceAddon-3.0.lua
Libs\AceConsole-3.0\AceConsole-3.0.lua
Libs\AceDB-3.0\AceDB-3.0.lua
Libs\AceEvent-3.0\AceEvent-3.0.lua
```

**Comment by mrmaffen** [comment]
Fixed in #https://github.com/mrmaffen/auto-open-anything/commit/7f7341bdd777053b11f690a1d6b3329213d1cece
Thanks!
