### ISSUE TITLE
190382 - Warped Pocket Dimension

### ISSUE THREAD

**Issue by Goss444** [mrmaffen/auto-open-anything#2]
When you loot 190382 - Warped Pocket Dimension the addon continuously tries to open this item. In process it spams the chat and the way the item works it creates a new item in your bag which prevents you from deleting or selling the item. The only way to get out of this loop is to disable the addon, reload, sell or delete the item then enable the addon with a reload.

I noticed the item is in the list of items to be opened, would it be possible to ignore this item or set it to not open by default?

**Comment by mrmaffen** [comment]
Done https://github.com/mrmaffen/auto-open-anything/commit/8d281235a6567e38cce8fb68db6545efb672548a
